### ISSUE TITLE
Changing bit precision (truncation bits)

### ISSUE THREAD

**Issue by xingpz2008** [OpenMined/sycret#57]
Hi,

I am currently trying to modify the sycret code in order to enable it on the truncated value,
i.e. generating keys with smaller alpha (and less bits) -> keys will be shorter -> evaluation will take less step
I have passed the test for rust code with a theoretical error probability.

However, when I try to test it with python, i.e. enable the stream parallelism then I could not passed the test because most of them are error.
I think there is something wrong with the stream part, but I didn't see anything I can do.

Do you have any idea that which part might be the problem¿

Thank you a lot!

@tholop

**Comment by tholop** [comment]
Thanks for your interest!
- What is the new number of bits? I guess that N=2 can make sense for the byte precision, but make sure to stay consistent if you start working in Z_{2^16}
- For the issue with Python, it's hard to tell but you should check that you are allocating memory properly with Numpy, and converting back to the proper type (maybe np.int32 if you are using N=2?)
- Finally, the stream parallelism actually happens in Rust, not Python. So you might want to double-check your casting and raw pointers here for instance: https://github.com/OpenMined/sycret/blob/6f745306fb7771a88981b1b61645029097a41174/src/stream.rs#L79 Maybe it's worth writing Rust tests for these stream functions too

Originally we wanted to have a generic N, but as you can see some functions (especially the memory wrappers) are implicitly hardcoding N=4. This is because we didn't have any reason to use a lower precision so we went with the most efficient implementation (e.g. we can use `u32` directly instead of working with vectors or arrays)

**Comment by xingpz2008** [comment]
Thank you for your reply!

I was trying to lower the bit by generating keys from a truncated alpha value , i.e. which alpha can be presented in a small ring exactly (maybe Z_{2^27} for example), so that the size of the key can be reduced because the number of CW, CW_leaf is connected with the bit number. Similarly, the evaluation step will be reduced as well because of the reduction of the bit number. 
In my specific implementation, I have changed the KeyLen from 32 to a smaller number.

To my best knowledge, the change mentioned above should be theoretically reasonable, so the error is weird to me……

**Comment by xingpz2008** [comment]
> Thanks for your interest!
> 
> * What is the new number of bits? I guess that N=2 can make sense for the byte precision, but make sure to stay consistent if you start working in Z_{2^16}
> * For the issue with Python, it's hard to tell but you should check that you are allocating memory properly with Numpy, and converting back to the proper type (maybe np.int32 if you are using N=2?)
> * Finally, the stream parallelism actually happens in Rust, not Python. So you might want to double-check your casting and raw pointers here for instance: https://github.com/OpenMined/sycret/blob/6f745306fb7771a88981b1b61645029097a41174/src/stream.rs#L79
>    Maybe it's worth writing Rust tests for these stream functions too
> 
> Originally we wanted to have a generic N, but as you can see some functions (especially the memory wrappers) are implicitly hardcoding N=4. This is because we didn't have any reason to use a lower precision so we went with the most efficient implementation (e.g. we can use `u32` directly instead of working with vectors or arrays)

Thank you for your reply!

I was trying to lower the bit by generating keys from a truncated alpha value , i.e. which alpha can be presented in a small ring exactly (maybe Z_{2^27} for example), so that the size of the key can be reduced because the number of CW, CW_leaf is connected with the bit number. Similarly, the evaluation step will be reduced as well because of the reduction of the bit number.
In my specific implementation, I have changed the KeyLen from 32 to a smaller number.

To my best knowledge, the change mentioned above should be theoretically reasonable, so the error is weird to me……

**Comment by tholop** [comment]
Yes, it is theoretically reasonable, but in practice our current implementation works with byte-level operations. So to make it work with 27 bits you will need to change more things than just the value of KeyLen -- basically rewrite the core functions, for instance with bit arrays instead of byte arrays and u32 outputs.

If you have a working prototype at some point feel free to open a pull request! I would be happy to have a look at your code and maybe merge it as an experimental feature for people who want to change the bit length.
